name: Auto-merge to main on develop update

on:
  push:
    branches:
      - develop

jobs:
  #Random name to identify the job
  merge-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        #Clone the repository
        uses: actions/checkout@v4
        #In develop branch
        with:
          ref: develop
          #Use the token from github profile on secrets variable
          token: ${{ secrets.GH_PAT }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn
        
      - name: Run tests
        run: yarn test

      #Give the configurations of github on VM
      - name: Set up Git
        #Use the bot from github actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge develop into main
        run: |
          git fetch origin main
          git checkout main
          git merge develop --allow-unrelated-histories -m "Merge develop into main"
          git push origin main
